// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjvuvqvanpzvgeosdhbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdnV2cXZhbnB6dmdlb3NkaGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMjU3NzcsImV4cCI6MjA1MjkwMTc3N30.WHZ_Cw-yV4rK4w9mQn5ruXtkNeTjoAAlWqvrWPK78Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);